### PR TITLE
feat: low hanging items + orbital logos first pass

### PR DESCRIPTION
**Pull request by jh3y**
## What was changed

- Add hover transition for links
- Remove headers from footer
- Switched out "Take me to the code" for button style
- Integrate Github Button for stars
- First pass at orbiting icons. Hidden at lower viewport sizing. Needs an OK on the copy, etc.

## Checklist

1. Closes 

2. How was this tested:

3. Any docs updates needed?

### CODE REVIEW

**Comment by sw-yx** [comment]
nice!! 

670px breakpoint is a little screwy
CleanShot 2021-06-10 at 02 00 09

**Comment by jh3y** [comment]
Ahh yes! Looks like the current site is a little broken at that point. I'll take a look and see what I can come up with 💯

**Comment by jh3y** [comment]
Should be good to go @sw-yx 🚀

**Comment by sw-yx** [comment]
woohoo!

**Comment by jh3y** [comment]
I need to have a think about how we "beg" 😅 

Some kind of non-intrusive way to draw attention to the stars is what I'm hoping for. I don't think we can change the staying too much of the button itself because it's what people know. But, if there's a way for us to point to it, that could be fun.

**Comment by sw-yx** [comment]
yup :) low priority, just noodle on it

**Pull request merged**
